In [7]:
#Create CSV file from given data. Read the data from CSV files into a data 
#frame. Perform Data pre-processing tasks such as handling missing 
#values and outliers using Python/R

#Multiple Linear Regression u


import pandas as pd
import numpy as np


data = {
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', 'Spain', 'France', 'Germany', 'France'],
    'Age': [44, 27, 30, 38, 40, 35, None, 48, 50, 37],  # Including one missing value (None)
    'Salary': [72000, 48000, 54000, 61000, None, 58000, 52000, 79000, 83000, 67000],  # One missing salary
    'Purchased': ['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)


df.to_csv("employee_data.csv", index=False)
df = pd.read_csv("employee_data.csv")
print("Original Data:\n", df)


df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("\nAfter Handling Missing Values:\n", df)

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return df[(df[column] >= lower) & (df[column] <= upper)]


df = remove_outliers(df, 'Age')
df = remove_outliers(df, 'Salary')

print("\nAfter Removing Outliers:\n", df)





import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error


data = {
    'Bedrooms': [3, 3, 2, 4, 3, 4, 3, 3, 1, 3],
    'Bathrooms': [1, 2.25, 1, 3, 2, 4.5, 2.25, 1.5, 1, 2.5],
    'Sqft_living': [1180, 2570, 770, 1960, 1680, 5420, 1715, 1060, 1780, 3560],
    'Floors': [1, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    'Grade': [7, 7, 6, 7, 8, 11, 7, 7, 7, 8],
    'Sqft_above': [1180, 2170, 770, 1050, 1680, 3890, 1715, 1060, 1050, 1860],
    'Sqft_basement': [0, 400, 0, 910, 0, 1530, 0, 0, 730, 1700],
    'Price': [221900, 538000, 180000, 604000, 510000, 267800, 257500, 291850, 229500, 662500]
}

df = pd.DataFrame(data)


X = df.drop('Price', axis=1)  
y = df['Price'] 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R² Score:", round(r2, 3))
print("Mean Squared Error:", round(mse, 2))
print("\nActual vs Predicted Prices:")
print(pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred.round(0)}))



import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error


data = {
    'Bedrooms': [3, 3, 2, 4, 3, 4, 3, 3, 1, 3],
    'Bathrooms': [1, 2.25, 1, 3, 2, 4.5, 2.25, 1.5, 1, 2.5],
    'Sqft_living': [1180, 2570, 770, 1960, 1680, 5420, 1715, 1060, 1780, 3560],
    'Floors': [1, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    'Grade': [7, 7, 6, 7, 8, 11, 7, 7, 7, 8],
    'Sqft_above': [1180, 2170, 770, 1050, 1680, 3890, 1715, 1060, 1050, 1860],
    'Sqft_basement': [0, 400, 0, 910, 0, 1530, 0, 0, 730, 1700],
    'Price': [221900, 538000, 180000, 604000, 510000, 267800, 257500, 291850, 229500, 662500]
}

df = pd.DataFrame(data)


X = df.drop('Price', axis=1)  
y = df['Price'] 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R² Score:", round(r2, 3))
print("Mean Squared Error:", round(mse, 2))
print("\nActual vs Predicted Prices:")
print(pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred.round(0)}))

Original Data:
    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

After Handling Missing Values:
    Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

After Removing Outliers:
    Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes
R² Score: -6.732
Mean Squared Error: 183967795202.06

Actual vs Predicted Prices:
   Actual  Predicted
0  229500   529076.0
1  538000    10563.0
R² Score: -6.732
Mean Squared Error: 183967795202.06

Actual vs Predicted Prices:
   Actual  Predicted
0  229500   529076.0
1  538000    10563.0

C:\Users\kirti\AppData\Local\Temp\ipykernel_5796\2809980143.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
C:\Users\kirti\AppData\Local\Temp\ipykernel_5796\2809980143.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)

R² Score: -6.732
Mean Squared Error: 183967795202.06

Actual vs Predicted Prices:
   Actual  Predicted
0  229500   529076.0
1  538000    10563.0